// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rewardsrefund.proto

package rewardsrefund

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{0}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{1}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type UserRefundRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RefundItemCost       int32    `protobuf:"varint,2,opt,name=refundItemCost,proto3" json:"refundItemCost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRefundRequest) Reset()         { *m = UserRefundRequest{} }
func (m *UserRefundRequest) String() string { return proto.CompactTextString(m) }
func (*UserRefundRequest) ProtoMessage()    {}
func (*UserRefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{2}
}

func (m *UserRefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRefundRequest.Unmarshal(m, b)
}
func (m *UserRefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRefundRequest.Marshal(b, m, deterministic)
}
func (m *UserRefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRefundRequest.Merge(m, src)
}
func (m *UserRefundRequest) XXX_Size() int {
	return xxx_messageInfo_UserRefundRequest.Size(m)
}
func (m *UserRefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRefundRequest proto.InternalMessageInfo

func (m *UserRefundRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRefundRequest) GetRefundItemCost() int32 {
	if m != nil {
		return m.RefundItemCost
	}
	return 0
}

type UserBalanceRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Balance              int32    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBalanceRequest) Reset()         { *m = UserBalanceRequest{} }
func (m *UserBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*UserBalanceRequest) ProtoMessage()    {}
func (*UserBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{3}
}

func (m *UserBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBalanceRequest.Unmarshal(m, b)
}
func (m *UserBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBalanceRequest.Marshal(b, m, deterministic)
}
func (m *UserBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBalanceRequest.Merge(m, src)
}
func (m *UserBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_UserBalanceRequest.Size(m)
}
func (m *UserBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserBalanceRequest proto.InternalMessageInfo

func (m *UserBalanceRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserBalanceRequest) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type UserRewardsRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Redemption           int32    `protobuf:"varint,2,opt,name=redemption,proto3" json:"redemption,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRewardsRequest) Reset()         { *m = UserRewardsRequest{} }
func (m *UserRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*UserRewardsRequest) ProtoMessage()    {}
func (*UserRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{4}
}

func (m *UserRewardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRewardsRequest.Unmarshal(m, b)
}
func (m *UserRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRewardsRequest.Marshal(b, m, deterministic)
}
func (m *UserRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRewardsRequest.Merge(m, src)
}
func (m *UserRewardsRequest) XXX_Size() int {
	return xxx_messageInfo_UserRewardsRequest.Size(m)
}
func (m *UserRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRewardsRequest proto.InternalMessageInfo

func (m *UserRewardsRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRewardsRequest) GetRedemption() int32 {
	if m != nil {
		return m.Redemption
	}
	return 0
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountBalance       int32    `protobuf:"varint,2,opt,name=accountBalance,proto3" json:"accountBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_31905ba79ee479ed, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAccountBalance() int32 {
	if m != nil {
		return m.AccountBalance
	}
	return 0
}

func init() {
	proto.RegisterType((*AddUserRequest)(nil), "AddUserRequest")
	proto.RegisterType((*ListUsersRequest)(nil), "ListUsersRequest")
	proto.RegisterType((*UserRefundRequest)(nil), "UserRefundRequest")
	proto.RegisterType((*UserBalanceRequest)(nil), "UserBalanceRequest")
	proto.RegisterType((*UserRewardsRequest)(nil), "UserRewardsRequest")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("rewardsrefund.proto", fileDescriptor_31905ba79ee479ed) }

var fileDescriptor_31905ba79ee479ed = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8a, 0xd3, 0x50,
	0x14, 0xc6, 0x49, 0x9c, 0x71, 0xf4, 0xe8, 0x74, 0xda, 0x33, 0x08, 0x75, 0x10, 0x19, 0xb2, 0x90,
	0x11, 0x21, 0xb1, 0x23, 0xe2, 0x4a, 0xc1, 0x76, 0x55, 0x10, 0x84, 0x48, 0x5d, 0x0a, 0xb7, 0xb9,
	0xa7, 0x25, 0xd0, 0xe6, 0xc6, 0x7b, 0x6f, 0xea, 0xa2, 0x64, 0xe3, 0x2b, 0xf8, 0x24, 0x3e, 0x8b,
	0xaf, 0xe0, 0x83, 0xc8, 0xfd, 0xa7, 0x4d, 0xeb, 0xa2, 0xcb, 0x7e, 0x3d, 0xdf, 0xef, 0x9c, 0xfb,
	0x7d, 0x04, 0x2e, 0x25, 0x7d, 0x63, 0x92, 0x2b, 0x49, 0x8b, 0xa6, 0xe2, 0x69, 0x2d, 0x85, 0x16,
	0x57, 0x4f, 0x96, 0x42, 0x2c, 0x57, 0x94, 0xb1, 0xba, 0xcc, 0x58, 0x55, 0x09, 0xcd, 0x74, 0x29,
	0x2a, 0xe5, 0xfe, 0x4d, 0xfa, 0xd0, 0x7b, 0xcf, 0xf9, 0x4c, 0x91, 0xcc, 0xe9, 0x6b, 0x43, 0x4a,
	0x27, 0x08, 0xfd, 0x0f, 0xa5, 0xd2, 0x46, 0x52, 0x41, 0xfb, 0x0c, 0x03, 0x37, 0x62, 0xb8, 0x5e,
	0xc4, 0xc7, 0x70, 0xd2, 0x28, 0x92, 0xc3, 0xe8, 0x3a, 0xba, 0x79, 0x70, 0x7b, 0x9a, 0xda, 0x09,
	0x2b, 0xe1, 0x33, 0xe8, 0xb9, 0x1b, 0xa6, 0x9a, 0xd6, 0x13, 0xa1, 0xf4, 0x30, 0xbe, 0x8e, 0x6e,
	0x4e, 0xf3, 0x3d, 0x35, 0x99, 0x02, 0x1a, 0xd7, 0x98, 0xad, 0x58, 0x55, 0xd0, 0x11, 0xe0, 0x21,
	0x9c, 0xcd, 0xdd, 0xb0, 0x27, 0x86, 0x9f, 0xc9, 0x47, 0x87, 0xca, 0x5d, 0x02, 0x47, 0xa0, 0x9e,
	0x02, 0x48, 0xe2, 0xb4, 0xae, 0x4d, 0x1c, 0x9e, 0xb6, 0xa3, 0x24, 0xef, 0xe0, 0xc4, 0x4c, 0x63,
	0x0f, 0xe2, 0x92, 0x5b, 0xc0, 0xfd, 0x3c, 0x2e, 0xb9, 0x79, 0x1b, 0x2b, 0x0a, 0xd1, 0x54, 0x7a,
	0xdc, 0xb9, 0x64, 0x4f, 0xbd, 0xfd, 0x79, 0x07, 0xce, 0x5d, 0x60, 0x9f, 0x48, 0x6e, 0xca, 0x82,
	0xf0, 0x35, 0x9c, 0xf9, 0xac, 0xf1, 0x22, 0xed, 0xa6, 0x7e, 0xe5, 0x4e, 0x4b, 0xf0, 0xfb, 0xaf,
	0xdf, 0x3f, 0xe2, 0x87, 0x08, 0xb6, 0x2e, 0x73, 0xa7, 0xc2, 0xb7, 0x70, 0x2f, 0x14, 0x82, 0x83,
	0x74, 0xbf, 0x9b, 0xe0, 0x7c, 0x64, 0x9d, 0x17, 0x78, 0x6e, 0x9d, 0x9b, 0x91, 0x33, 0xbf, 0x8c,
	0x70, 0x01, 0xfd, 0x89, 0x24, 0xa6, 0xe9, 0x5f, 0x83, 0x88, 0xe9, 0x41, 0x9d, 0x81, 0xf3, 0xc6,
	0x72, 0x46, 0x98, 0x05, 0x4e, 0x61, 0xcd, 0x6e, 0x36, 0xdb, 0x1a, 0x6a, 0x5a, 0xf2, 0x36, 0xdb,
	0x76, 0xab, 0x6c, 0x71, 0x0e, 0x83, 0x59, 0xcd, 0xfd, 0x1e, 0x1f, 0x02, 0x5e, 0xa6, 0x87, 0xfd,
	0x86, 0x4d, 0x23, 0xbb, 0xe9, 0x05, 0x3e, 0xff, 0x7b, 0xb1, 0xb5, 0xfb, 0xe1, 0xdd, 0x55, 0xbe,
	0xe3, 0x16, 0xbf, 0x98, 0x48, 0x39, 0xd1, 0xda, 0xd7, 0xec, 0xf9, 0xdd, 0xd2, 0xff, 0xcf, 0x97,
	0xbb, 0xbe, 0xee, 0x3b, 0x42, 0xe5, 0xed, 0xfc, 0xae, 0xfd, 0x28, 0x5e, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0x7d, 0xb1, 0x7f, 0x49, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RefundServiceClient is the client API for RefundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RefundServiceClient interface {
	// Add a user
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error)
	// Lists users
	ListUser(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (RefundService_ListUserClient, error)
	CreateUserRefund(ctx context.Context, in *UserRefundRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUserBalance(ctx context.Context, in *UserBalanceRequest, opts ...grpc.CallOption) (*User, error)
	RedeemRewards(ctx context.Context, in *UserRewardsRequest, opts ...grpc.CallOption) (*User, error)
}

type refundServiceClient struct {
	cc *grpc.ClientConn
}

func NewRefundServiceClient(cc *grpc.ClientConn) RefundServiceClient {
	return &refundServiceClient{cc}
}

func (c *refundServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/RefundService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundServiceClient) ListUser(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (RefundService_ListUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RefundService_serviceDesc.Streams[0], "/RefundService/ListUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &refundServiceListUserClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RefundService_ListUserClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type refundServiceListUserClient struct {
	grpc.ClientStream
}

func (x *refundServiceListUserClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *refundServiceClient) CreateUserRefund(ctx context.Context, in *UserRefundRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/RefundService/CreateUserRefund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundServiceClient) UpdateUserBalance(ctx context.Context, in *UserBalanceRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/RefundService/UpdateUserBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *refundServiceClient) RedeemRewards(ctx context.Context, in *UserRewardsRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/RefundService/RedeemRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundServiceServer is the server API for RefundService service.
type RefundServiceServer interface {
	// Add a user
	AddUser(context.Context, *AddUserRequest) (*User, error)
	// Lists users
	ListUser(*ListUsersRequest, RefundService_ListUserServer) error
	CreateUserRefund(context.Context, *UserRefundRequest) (*User, error)
	UpdateUserBalance(context.Context, *UserBalanceRequest) (*User, error)
	RedeemRewards(context.Context, *UserRewardsRequest) (*User, error)
}

// UnimplementedRefundServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRefundServiceServer struct {
}

func (*UnimplementedRefundServiceServer) AddUser(ctx context.Context, req *AddUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedRefundServiceServer) ListUser(req *ListUsersRequest, srv RefundService_ListUserServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}
func (*UnimplementedRefundServiceServer) CreateUserRefund(ctx context.Context, req *UserRefundRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserRefund not implemented")
}
func (*UnimplementedRefundServiceServer) UpdateUserBalance(ctx context.Context, req *UserBalanceRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserBalance not implemented")
}
func (*UnimplementedRefundServiceServer) RedeemRewards(ctx context.Context, req *UserRewardsRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemRewards not implemented")
}

func RegisterRefundServiceServer(s *grpc.Server, srv RefundServiceServer) {
	s.RegisterService(&_RefundService_serviceDesc, srv)
}

func _RefundService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RefundService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundService_ListUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RefundServiceServer).ListUser(m, &refundServiceListUserServer{stream})
}

type RefundService_ListUserServer interface {
	Send(*User) error
	grpc.ServerStream
}

type refundServiceListUserServer struct {
	grpc.ServerStream
}

func (x *refundServiceListUserServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _RefundService_CreateUserRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).CreateUserRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RefundService/CreateUserRefund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).CreateUserRefund(ctx, req.(*UserRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundService_UpdateUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).UpdateUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RefundService/UpdateUserBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).UpdateUserBalance(ctx, req.(*UserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RefundService_RedeemRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServiceServer).RedeemRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RefundService/RedeemRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServiceServer).RedeemRewards(ctx, req.(*UserRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RefundService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RefundService",
	HandlerType: (*RefundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _RefundService_AddUser_Handler,
		},
		{
			MethodName: "CreateUserRefund",
			Handler:    _RefundService_CreateUserRefund_Handler,
		},
		{
			MethodName: "UpdateUserBalance",
			Handler:    _RefundService_UpdateUserBalance_Handler,
		},
		{
			MethodName: "RedeemRewards",
			Handler:    _RefundService_RedeemRewards_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUser",
			Handler:       _RefundService_ListUser_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rewardsrefund.proto",
}
